# Generated by Django 3.2.7 on 2021-12-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='static/uploads/avatar/%Y/%m'),
        ),
    ]
