# Generated by Django 3.2.7 on 2021-12-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_alter_weddinghalls_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=None, upload_to='static/food/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=None, upload_to='static/menu/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=None, upload_to='static/service/%Y/%m'),
        ),
    ]
